title: Limehouse Labs
description: >-
  Limehouse Labs is a small collaborative workshop based at Limehouse Town Hall in London.
baseurl: ""
url: "https://www.limehouselabs.org"
lang: en_GB

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
